[package]
name = "syn-lite"
version = "0.1.1"
edition = "2021"
description = "limited but lite syntax parsing with only macro_rules"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
