on:
  push:
    branches:
      - main
name: release-please
env:
  CARGO_TERM_COLOR: always
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: rust
          package-name: syn-lite

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - name: Build
        run: cargo build --verbose
        if: ${{ steps.release.outputs.release_created }}
      - name: Run tests
        run: cargo test --verbose --all-targets
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
